version: "3"
services:
  dnsmasq:
    build: .
    ports:
      - 53:53/tcp
      - 53:53/udp
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./volumes/dnsmasq.conf:/etc/dnsmasq.conf